include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_luffy_wanted #update entry
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_luffy_wanted #update entry
